/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javapractice;

import java.awt.Color;

/**
 *
 * @author Malhotra Computer
 */
public class JFramePractice extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePractice.class.getName());

    /**
     * Creates new form JFramePractice
     */
    public JFramePractice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addmemberPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        texthome = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        textaddmembers = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        textdelete = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("PRACTICE  SHEET");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 30));

        addmemberPanel.setBackground(new java.awt.Color(204, 204, 0));
        addmemberPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addmemberPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addmemberPanelMouseExited(evt);
            }
        });

        homePanel.setBackground(new java.awt.Color(204, 204, 0));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homePanelMouseExited(evt);
            }
        });
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texthome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        texthome.setText("HOME");
        homePanel.add(texthome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        jPanel6.setBackground(new java.awt.Color(204, 204, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        homePanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, -1, -1));

        jPanel5.setAlignmentY(0.5F);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textaddmembers.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        textaddmembers.setText("ADD MEMBERS");

        deletePanel.setBackground(new java.awt.Color(204, 204, 0));
        deletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textdelete.setText("DELETE M.");
        textdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textdeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textdeleteMouseExited(evt);
            }
        });
        deletePanel.add(textdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 6, 58, 31));

        javax.swing.GroupLayout addmemberPanelLayout = new javax.swing.GroupLayout(addmemberPanel);
        addmemberPanel.setLayout(addmemberPanelLayout);
        addmemberPanelLayout.setHorizontalGroup(
            addmemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmemberPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(addmemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addmemberPanelLayout.createSequentialGroup()
                        .addComponent(textaddmembers, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberPanelLayout.createSequentialGroup()
                        .addGroup(addmemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
            .addGroup(addmemberPanelLayout.createSequentialGroup()
                .addComponent(deletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        addmemberPanelLayout.setVerticalGroup(
            addmemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmemberPanelLayout.createSequentialGroup()
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textaddmembers, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(addmemberPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseEntered
        // TODO add your handling code here:
        Color color = new Color(153,153,0);
        homePanel.setBackground(color);
        texthome.setForeground(color.white);
    }//GEN-LAST:event_homePanelMouseEntered

    private void addmemberPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmemberPanelMouseEntered
        // TODO add your handling code here:
        Color color = new Color(153,153,0);
        addmemberPanel.setBackground(color);
        textaddmembers.setForeground(color.white);

    }//GEN-LAST:event_addmemberPanelMouseEntered

    private void homePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseExited
        // TODO add your handling code here:
        Color color = new Color(153,153,0);
        texthome.setForeground(color.BLACK);
        homePanel.setBackground(color);
    }//GEN-LAST:event_homePanelMouseExited

    private void addmemberPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmemberPanelMouseExited
        // TODO add your handling code here:
        Color color = new Color(153,153,0);
        textaddmembers.setForeground(color.BLACK);
        addmemberPanel.setBackground(color);
    }//GEN-LAST:event_addmemberPanelMouseExited

    private void textdeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textdeleteMouseEntered
        // TODO add your handling code here:
        Color color = new Color(153,153,0);
        deletePanel.setBackground(color);
        textdelete.setForeground(color.white);
    }//GEN-LAST:event_textdeleteMouseEntered

    private void textdeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textdeleteMouseExited
        // TODO add your handling code here:
        Color color = new Color(153,153,0);
        textdelete.setForeground(color.BLACK);
        deletePanel.setBackground(color);
    }//GEN-LAST:event_textdeleteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFramePractice().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addmemberPanel;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel textaddmembers;
    private javax.swing.JLabel textdelete;
    private javax.swing.JLabel texthome;
    // End of variables declaration//GEN-END:variables
}
